language: python
dist: xenial
os: linux
git:
  depth: 3
  submodules: true

deploy:
  provider: script
  script: bash travis/upload.sh
  on:
    tags: true
    branch: master

env:
  global:
  - secure: RsaS50aaL+dvUcmzicm75MB+15gDj/XuXxJ2j078virJG1I0EyTn0koPsvQQD6lD1nATPTn0hPG4uIjh5l0madlyCel/Q2cmtPGkBnZ0RX1C8dq0RUwVIzE0gghmsfMW+OxmxGjbdnwTWHiqtM8IFIk41oDMLCn5lMXYKhMsTLnyURjCJdDxySVZ+Q3JORcWgLV/YUnBL9IoElKSzVAdPLf2pDdtuvNmvkhaeaA0PkBLnNCed1LaGvwR8Rzc78+oEssYJUIUEH5TXQwxvmitSYd+VXxh7QzOJ6VK70wk14y7mj1dXDxJoPmpJnnPF8aGSr63vKLcgVYYH8n85jz3JNV1v7alSB1Vn9EOGgtRxVm1FMfXiaq/emvUZlonixC73AkcwhfV0lQX9Qs01hLBo6TdbsRX9DwNHSfLwUK41WXd5YNFY/Sswd2OTNUnFzGUlfZt05tURgh9inL1al4a7axxILH8y17d+n2UtDTZc/S01VF11wzKxavpSPQkOODuTbLczcX0x5E1LX54cE9htbK1FKlFRPAQ898DkeGadGI4n9G30OQ+ZWBe6m2TszaGuy6cZpeKZcQRin2ni/pdJfqAiqTqs+0i4G11VD7FQ0Z6U2GeKLPxJlZIMhpZdYlNVQ1JAMFyjcJeRl2TwP21gc76805XNfayhynTO4Xd7w0=
  - secure: Hr2QgjQI6Xf+2UTXJx18KityngUzsOIo/0tHkXwjAZBT9IsAol2u9uyDD1b1WjqH2/78EJt/+Eho/ONpbVlggbdeSr84vQW1ASAIvHwqjSv6QNRmFUyE162THsVd5udvOqB9zOJcYJN4FN5nt4GpaAFNnZHh7oLaOdq9jTxI6KO3nx79RY2uyXzRfCpeNDUeAyCKs+cIwiE34B3bz3h7FsuE0c/0KRK6IJwEEFS0Zkgzwl/vclids0TvECJsmcuO4tmwi0rH6T4ohKj6KofD9k2En2xhaVWKseBsFWoEFKbwGxTkdX9t37p/XmXFmCbDeiE8ZEUYvH2QJiyAzQ7d1e6SWW9khLnoZFUIGewA9hdTybJOVJEsWOzEvMp/wvWBtwnQmxNIHRdITS/xTtz6+S6HesSsri0zP+ULWcVSLNdBh36DyDLBTXVhUYSe6YiWMkfhw41/varGj5IpOj7aCVxKv6fwggL8kT6EUqz+YYInJO2eKiaEgXy4fmVBIkZB1pexhxDNJZsGD7tKkQ1gZLC90VEz6O0z6qFSnI3hZHUo+9xE3ylvp/n8buRLnAVr4faAuRHPNQAqfmr1sXA0i2mqnXDlWxIvvvgFT62dDyS5AzIpmXqwaCpR0iVLKuiVIlR+AfW8cMuFDNkh8anzptFyk+3iULYq8g5VHGi4KaE=

jobs:
  include:
  - name: Python 3.7.7 on macOS (xcode 11.2)
    os: osx
    osx_image: xcode11.2
    language: shell
  - name: manylinux1 x86_64
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
  - name: manylinux1 i686
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686
  - name: manylinux2010 x86_64
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64

before_install:
  - python3 -V
  - git fetch --tags

install:
  - mkdir wheelhouse
  - travis/install.sh

script:
  - travis/script.sh
  - ls wheelhouse/ -l
