name: Build and test all wheels
on:
  push:
    branches:
      master

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    runs-on: ${{ matrix.os }}
    name: build and test wheels on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build x86_64 wheels
        uses: pypa/cibuildwheel@v3.4.1
        with:
          config-file: "pyproject.toml"

      - name: upload wheel artifacts temporarily
        uses: actions/upload-artifact@v4
        with:
          name: cliquematch-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          retention-days: 1
