name: Build and test all wheels
on:
  push:
    branches:
      master

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    name: build and test wheels on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.3
        env:
          CIBW_SKIP: "cp-310*"
          CIBW_SKIP: "pp*"
          CIBW_BUILD_FRONTEND: "pip"
          CIBW_BEFORE_BUILD: "python -m pip install numpy>=1.14 pybind11>=2.2 --prefer-binary"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest -v {project}"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"

      - name: View generated wheels
        run: ls -al ./wheelhouse
